### ISSUE TITLE
ParVector::SubAvg

### ISSUE THREAD

**Issue by chakshinglee** [gelever/parlinalgcpp#11]
In SubAvg, should `LocalSum()` be `GlobalSum()`?

https://github.com/gelever/parlinalgcpp/blob/92044137c488bd6b70542c0f1848051dca9010a7/src/parvector.cpp#L181-L184

**Comment by gelever** [comment]
Yes, good catch.  I probably haven't run into this yet because I actually haven't need `ParVector` anywhere (since `ParOperator` can `Mult` regular `VectorViews`).
